# Generated by Django 3.0.7 on 2020-06-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='aciklama',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
