# Generated by Django 3.0.7 on 2020-07-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20200702_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='kategori',
            field=models.CharField(default='#Kategorisiz', max_length=30),
        ),
    ]
