# Generated by Django 3.0.7 on 2020-07-02 11:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20200702_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tarih',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 2, 11, 42, 35, 305765, tzinfo=utc)),
        ),
    ]
