# Generated by Django 3.0.7 on 2020-07-02 13:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20200702_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tarih',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 2, 13, 37, 40, 570571, tzinfo=utc)),
        ),
    ]
