# Generated by Django 3.0.7 on 2020-07-03 06:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20200702_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='kategori',
            field=models.CharField(default='#Kateqoriyasiz', max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='tarih',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 3, 6, 31, 35, 183759, tzinfo=utc)),
        ),
    ]
