# Generated by Django 3.0.7 on 2020-07-06 14:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20200703_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tarih',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 6, 14, 29, 26, 228417, tzinfo=utc)),
        ),
    ]
