# Generated by Django 3.0.7 on 2020-07-07 00:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20200706_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tarih',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 7, 0, 54, 4, 259412, tzinfo=utc)),
        ),
    ]
