# Generated by Django 3.0.7 on 2020-07-07 02:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20200707_0554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-tarih']},
        ),
        migrations.AlterField(
            model_name='post',
            name='kategori',
            field=models.CharField(default='Kateqoriyasiz', max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='tarih',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 7, 2, 5, 56, 435068, tzinfo=utc)),
        ),
    ]
