# Generated by Django 3.0.7 on 2020-07-07 02:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20200707_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tarih',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 7, 2, 11, 18, 885679, tzinfo=utc)),
        ),
    ]
