# Generated by Django 3.0.7 on 2020-07-07 05:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_auto_20200707_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tarih',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 7, 5, 58, 24, 45174, tzinfo=utc)),
        ),
    ]
