# Generated by Django 3.0.7 on 2020-07-09 10:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_auto_20200707_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='resim',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='tarih',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 9, 10, 30, 37, 941599, tzinfo=utc)),
        ),
    ]
