# Generated by Django 3.0.7 on 2020-07-10 17:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_auto_20200709_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tarih',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 10, 17, 19, 53, 666581, tzinfo=utc)),
        ),
    ]
