# Generated by Django 3.0.8 on 2020-07-25 16:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_auto_20200710_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deneme',
            field=models.ManyToManyField(related_name='_post_deneme_+', to='post.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tarih',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 25, 16, 17, 21, 454931, tzinfo=utc)),
        ),
    ]
