# Generated by Django 3.0.8 on 2020-07-25 16:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0022_auto_20200725_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='deneme',
        ),
        migrations.AlterField(
            model_name='post',
            name='tarih',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 25, 16, 19, 11, 574494, tzinfo=utc)),
        ),
    ]
