# Generated by Django 3.0.8 on 2020-07-31 07:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0025_auto_20200729_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='favori',
        ),
        migrations.AlterField(
            model_name='post',
            name='tarih',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 7, 51, 22, 356208, tzinfo=utc)),
        ),
    ]
